The following line threw a NotImplementedError exception:
t0 = hard_em(semi_supervised_labeled, semi_supervised_unlabeled, 0)
-------
The following line threw a NotImplementedError exception:
tk = hard_em(semi_supervised_labeled, semi_supervised_unlabeled, 3)
-------
The following line threw a NameError exception: name 't0' is not defined:
t0_acc = compute_acc(t0, test_data_universal, print_mistakes=False)
-------
The following line threw a NameError exception: name 'tk' is not defined:
tk_acc = compute_acc(tk, test_data_universal, print_mistakes=False)
-------
The following line threw a NameError exception: name 't0_acc' is not defined:
print('\nTagging accuracy of T_0: %.4f' % (t0_acc))
-------
The following line threw a NameError exception: name 'tk_acc' is not defined:
print('\nTagging accuracy of T_k: %.4f' % (tk_acc))
-------
The following line threw a NotImplementedError exception: answer_question4b:
bad_tags, good_tags, answer4b = answer_question4b()
-------
The following line threw a NameError exception: name 'bad_tags' is not defined:
print(bad_tags)
-------
The following line threw a NameError exception: name 'good_tags' is not defined:
print(good_tags)
-------
The following line threw a NameError exception: name 'answer4b' is not defined:
print(answer4b)
-------
The following line threw a NotImplementedError exception: answer_question5b:
answer5b = answer_question5b()
-------
The following line threw a NameError exception: name 'answer5b' is not defined:
print(answer5b)
-------
The following line threw a NotImplementedError exception: answer_question6:
answer6 = answer_question6()
-------
The following line threw a NameError exception: name 'answer6' is not defined:
print(answer6)
-------
The following line threw a NotImplementedError exception: answer_question7:
answer7 = answer_question7()
-------
The following line threw a NameError exception: name 'answer7' is not defined:
print(answer7)
-------
Exception in answer dict value computation:
    bad_tags -> NameError("name 'bad_tags' is not defined")
  File "/home/hwixley/Documents/4th-Year/FNLP/cwk2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    good_tags -> NameError("name 'good_tags' is not defined")
  File "/home/hwixley/Documents/4th-Year/FNLP/cwk2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    answer4b -> NameError("name 'answer4b' is not defined")
  File "/home/hwixley/Documents/4th-Year/FNLP/cwk2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    t0_acc -> NameError("name 't0_acc' is not defined")
  File "/home/hwixley/Documents/4th-Year/FNLP/cwk2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    tk_acc -> NameError("name 'tk_acc' is not defined")
  File "/home/hwixley/Documents/4th-Year/FNLP/cwk2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    answer5b -> NameError("name 'answer5b' is not defined")
  File "/home/hwixley/Documents/4th-Year/FNLP/cwk2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    answer6 -> NameError("name 'answer6' is not defined")
  File "/home/hwixley/Documents/4th-Year/FNLP/cwk2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    answer7 -> NameError("name 'answer7' is not defined")
  File "/home/hwixley/Documents/4th-Year/FNLP/cwk2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
